service: carbontracker-backend-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless
package:
  artifact: target/hello-dev.jar

functions:
  carbon-api:
    handler: com.serverless.Handler
    events:
      - http:
          path: calculatecarbon
          method: get
