service: carbontracker-backend-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless
  apiGateway:
    shouldStartNameWithService: true
package:
  artifact: target/carbon-api-dev.jar


functions:
  get-initial-carbon-api:
    handler: com.thinktech.GetInitialCarbonHandler
    events:
      - http:
          path: initialcarbon
          method: get
  get-tracking-carbon-api:
    handler: com.thinktech.GetTrackingCarbonHandler
    events:
      - http:
          path: /users/{userId}/trackingcarbon
          method: get
