service: carbontracker-backend-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless
  apiGateway:
    shouldStartNameWithService: true
  environment:
    "DB_HOST": ${file(./config.dev.json):DB_HOST}
    "DB_NAME": ${file(./config.dev.json):DB_NAME}
    "DB_USER": ${file(./config.dev.json):DB_USER}
    "DB_PASSWORD": ${file(./config.dev.json):DB_PASSWORD}
package:
  artifact: target/carbon-api-dev.jar

functions:
  calc-initial-carbon-api:
    handler: com.thinktech.CalculateInitialCarbonHandler
    events:
      - http:
          path: initialcarbon
          method: post
  get-tracking-carbon-api:
    handler: com.thinktech.GetTrackingCarbonHandler
    events:
      - http:
          path: /users/{userId}/trackingcarbon
          method: get
  add-user-carbon-api:
    handler: com.thinktech.AddUserCarbonHandler
    events:
      - http:
          path: /users/{userId}/adduser
          method: post
  get-tracking-carbon-for-month-api:
    handler: com.thinktech.GetTrackingCarbonForMonthHandler
    events:
      - http:
          path: /trackingcarbonformonth
          method: get